### ISSUE TITLE
[FEATURE REQUEST] Multiple Targets

### ISSUE THREAD

**Issue by webdawg** [dennypage/dpinger#24] opened 2017-06-22 13:28 UTC
Background:

*https://redmine.pfsense.org/issues/4354
*https://redmine.pfsense.org/issues/1189

There is even this now:  https://forum.pfsense.org/index.php?topic=123741.0

$2500 bounty.

Feature request:  Multiple Targets To Ping

So the most basic feature to ask for in relation to multiple targets in dpinger I would think is:  that if all ips are down then pfsense (dpinger) could mark the connection as down.  I have a few devices out in the field and sometimes pings just stop to a target until they are restarted/re routed.

I think also that this should be a feature because of the way broadband ISP's seem to handle pings anymore.  Even on a few 'business' connections I will see dropped pings to an ISP gateway, like they just kill the pings or routes that have to do with icmp.

I have had anycast IP's stop pinging too, when a connection is just fine.  I think it stems from just crap routing and traffic management setups, where ISP's just do not care about this type of traffic anymore.

I have quite a few dedis and VPS's in the wild but I cannot guarantee 100% uptime on all at the same time, but I can guarantee that at least 8 out of 10 will be up, or 5 out of 10.

I really do think that this is a valid request for a piece of software like this anymore as it is more and more common for small business level internet to have issues with pings.  I have had routers in at least 10 different locations across 10 different states, with 10 different ISP's all have issues like this.  Time Warner, Spectrum, ATT, Verizon DSL, Verizon 4G, Comcast, FIOS, Brighthouse, Misc WISP, etc etc.

This issue @ pfsense has been open for 6 years now and I know it might not be as glamorous as fast kernel space packet routing but anymore this is a huge problem.  I have clients dumping money into the pfsense project via hardware and support purchases only to have unreliable broadband because of this.

I am not 100% in tune to the relationship between dpinger and pfsense but it was suggested by Mr Thompson to come here and ask for something like this.  Please help.

**Comment by dennypage** [comment] 2017-06-22 15:22
See issue request 22

https://github.com/dennypage/dpinger/issues/22

**Comment by dennypage** [comment] 2017-06-22 15:23
Duplicate of #22

**Closed as completed by dennypage** 2017-06-22 15:23 UTC
Labels: duplicate
